current_run:
  device: 0,1,2,3,4,5,6,7
  scenario_type: optimized
  torch_profile: true
  torch_profiler_light: true
  profile_detail: light
  torch_with_stack: false
  torch_record_shapes: false
  torch_profile_memory: false
  torch_with_modules: false
model:
  path: /data/models/DeepSeek-V4-Flash-FP8
  name: DeepSeek-V4-Flash-FP8-TP8-P8192D256C32
  tokenizer_path: /data/models/DeepSeek-V4-Flash-FP8
  tensor_parallel_size: 8
serve: {}
sglang:
  context_length: 16384
  mem_fraction_static: 0.75
  load_format: safetensors
  trust_remote_code: true
  extra_args: --skip-server-warmup --skip-warmup --max-total-tokens 655360 --max-running-requests 32 --swa-full-tokens-ratio 0.50 --chunked-prefill-size 8192 --max-prefill-tokens 8192 --disable-radix-cache --disable-chunked-prefix-cache --disable-overlap-schedule --cuda-graph-backend-decode disabled --cuda-graph-backend-prefill disabled --random-range-ratio 1.0 --sampling-backend pytorch --dist-timeout 1800 --watchdog-timeout 3600 --port 30001 --nccl-port 29501
benchmark:
  dataset_name: random
  dataset_path: /data/yangkw/datasets/sharegpt_synthetic_2048.json
  num_runs: 2
  scenarios:
    optimized:
      - name: p8192d256_c32
        input_len: 8192
        output_len: 256
        concurrency: 32
  host: 127.0.0.1
paths:
  results: results
  reports: reports
  use_model_name: true
  log_dir: results/DeepSeek-V4-Flash-FP8-TP8-P8192D256C32/sglang-bench_optimized_torch_profile_log/sglang_bench_logs
  torch_output_dir: results/DeepSeek-V4-Flash-FP8-TP8-P8192D256C32/sglang-torch-raw
  reports_dir: reports/DeepSeek-V4-Flash-FP8-TP8-P8192D256C32
  model_name: DeepSeek-V4-Flash-FP8-TP8-P8192D256C32
